<?php
namespace TYPO3\Flow\Persistence\Doctrine\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
	Doctrine\DBAL\Schema\Schema;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20141126145932 extends AbstractMigration {

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function up(Schema $schema) {
		// this up() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE gib_gradingtool_domain_model_project ADD datasheetformidentifier VARCHAR(255) NOT NULL, ADD submissionformidentifier VARCHAR(255) NOT NULL, CHANGE uid uid INT(11) NOT NULL AUTO_INCREMENT UNIQUE");
		$this->addSql("UPDATE gib_gradingtool_domain_model_project SET datasheetformidentifier='dataSheetForm', submissionformidentifier='submissionForm'");
	}

	/**
	 * @param Schema $schema
	 * @return void
	 */
	public function down(Schema $schema) {
		// this down() migration is autogenerated, please modify it to your needs
		$this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");
		
		$this->addSql("ALTER TABLE gib_gradingtool_domain_model_project DROP datasheetformidentifier, DROP submissionformidentifier, CHANGE uid uid INT AUTO_INCREMENT NOT NULL");
	}
}
