-
  name: 'GIB.GradingTool Home'
  uriPattern: ''
  defaults:
    '@package': 'GIB.GradingTool'
    '@controller': 'Standard'
    '@action': 'index'

-
  name: 'GIB.GradingTool :: Project'
  uriPattern: 'project/newdatasheet'
  defaults:
    '@package': 'GIB.GradingTool'
    '@controller': 'Project'
    '@action': 'newDataSheet'
  appendExceedingArguments: true

-
  name: 'GIB.GradingTool :: Project :: Edit Data Sheet'
  uriPattern: 'project/{project}/editdatasheet'
  defaults:
    '@package':    'GIB.GradingTool'
    '@controller': 'Project'
    '@action':     'editDataSheet'

-
  name: 'GIB.GradingTool :: Project :: Edit Project Data'
  uriPattern: 'project/{project}/editprojectdata'
  defaults:
    '@package':    'GIB.GradingTool'
    '@controller': 'Project'
    '@action':     'editProjectData'

-
  name: 'GIB.GradingTool :: Project :: Review Data Sheet'
  uriPattern: 'project/{project}/reviewdatasheet'
  defaults:
    '@package':    'GIB.GradingTool'
    '@controller': 'Project'
    '@action':     'reviewDataSheet'

-
  name: 'GIB.GradingTool :: Project :: Remove Project'
  uriPattern: 'project/{project}/remove'
  defaults:
    '@package':    'GIB.GradingTool'
    '@controller': 'Project'
    '@action':     'remove'

-
  name: 'GIB.GradingTool :: Project :: Deactivate Submission'
  uriPattern: 'project/{project}/deactivategrading'
  defaults:
    '@package':    'GIB.GradingTool'
    '@controller': 'Project'
    '@action':     'deactivateSubmissionForm'

-
  name: 'GIB.GradingTool :: Project :: Activate Submission'
  uriPattern: 'project/{project}/activategrading'
  defaults:
    '@package':    'GIB.GradingTool'
    '@controller': 'Project'
    '@action':     'activateSubmissionForm'


-
  name: 'GIB.GradingTool :: Project :: Edit Submission'
  uriPattern: 'project/{project}/grading'
  defaults:
    '@package':    'GIB.GradingTool'
    '@controller': 'Project'
    '@action':     'submission'

-
  name: 'GIB.GradingTool :: Project :: Review Submission'
  uriPattern: 'project/{project}/reviewgrading'
  defaults:
    '@package':    'GIB.GradingTool'
    '@controller': 'Project'
    '@action':     'reviewSubmission'

-
  name: 'GIB.GradingTool :: Project :: Export Report'
  uriPattern: 'project/{project}/exportreport'
  defaults:
    '@package':    'GIB.GradingTool'
    '@controller': 'Project'
    '@action':     'exportReport'

-
  name: 'GIB.GradingTool Admin'
  uriPattern: 'admin/{@action}'
  defaults:
    '@package': 'GIB.GradingTool'
    '@controller': 'Admin'
  appendExceedingArguments: true

-
  name: 'GIB.GradingTool Template'
  uriPattern: 'template/{@action}'
  defaults:
    '@package': 'GIB.GradingTool'
    '@controller': 'Template'
  appendExceedingArguments: true

-
  name: 'GIB.GradingTool Database'
  uriPattern: 'database'
  defaults:
    '@package': 'GIB.GradingTool'
    '@controller': 'Database'
    '@action': 'index'
  appendExceedingArguments: true

-
  name: 'GIB.GradingTool Open Project'
  uriPattern: 'database/{project}/open'
  defaults:
    '@package': 'GIB.GradingTool'
    '@controller': 'Database'
    '@action': 'open'
  routeParts:
    project:
      objectType: 'GIB\GradingTool\Domain\Model\Project'
      uriPattern: '{projectTitle}'
#-
#  name: 'GIB Export PDF'
#  uriPattern: 'gib.gradingtool/standard/export.{@format}'
#  defaults:
#    '@package':    'GIB.GradingTool'
#    '@controller': 'Standard'
#    '@action':     'export'
#    '@format':     'pdf'