GIB:
  GradingTool:
    dataSheetPresetName: 'gibdatasheet'

TYPO3:
  Form:
    presets:
      gibdatasheet:
        title: 'GIB Data Sheet'
        parentPreset: 'default'

        ########### Required CSS / JavaScripts ###########

        stylesheets:
          bootstrap:
            source: 'resource://GIB.GradingTool/Public/Stylesheets/bootstrap.min.css'
        javaScripts: []

        ########### DEFAULT FORM ELEMENT DEFINITIONS ###########
        formElementTypes:

          ### BASE ELEMENTS ###

          # NAMING: base class for everything is RENDERABLE
          'TYPO3.Form:Base':
            renderingOptions:
              templatePathPattern: 'resource://GIB.GradingTool/Private/Form/{@type}.html'
              partialPathPattern: 'resource://GIB.GradingTool/Private/Form/Partials/{@type}.html'
              layoutPathPattern: 'resource://GIB.GradingTool/Private/Form/Layouts/{@type}.html'
              # set this to TRUE if you want to avoid exceptions for FormElements without definitions
              skipUnknownElements: FALSE
              # Package with XLIFF files for translatable messages (e.g. validation errors)
              # If you need custom messages, copy Resources/Private/Translations/en/ValidationErrors.xlf to your package and adjust this setting
              translationPackage: 'TYPO3.Flow'

          'TYPO3.Form:Form':
            formBuilder:
              editors:
                finishers:
                  availableFinishers:
                    'GIB.GradingTool:ProjectSerializedStorageFinisher':
                      label: 'Save serialized data to project'
                      templateName: 'Finisher-GIB.GradingTool-ProjectSerializedStorageFinisher'
        ### FINISHERS ###
        finisherPresets:
          'GIB.GradingTool:ProjectSerializedStorageFinisher':
            implementationClassName: 'GIB\GradingTool\Form\Finishers\ProjectSerializedStorageFinisher'
      gibdatasheetedit:
        title: 'GIB Data Sheet Edit Form'
        parentPreset: 'gibdatasheet'
        formElementTypes:
          'TYPO3.Form:FormElement':
            superTypes: ['TYPO3.Form:Base', 'TYPO3.Form:RemovableMixin']
            implementationClassName: 'GIB\GradingTool\Form\FormElements\EditableGenericFormElement'
  FormBuilder:
    handlebarsTemplates:
      Finisher-GIB.GradingTool-ProjectSerializedStorageFinisher: 'resource://GIB.GradingTool/Private/FormBuilderTemplates/Finisher/ProjectSerializedStorageEditor.html'




